[build]
  command = "npm run build"
  publish = "dist"

[context.production.environment]
  NEXT_SERVERLESS = "true"
  APP_ENV = "production"
  NODE_VERSION = "14.7.0"
  NPM_VERSION = "7.8.0"

[[plugins]]
  package = "/plugins/gen-next-config"
[[plugins]]
  package = "@netlify/plugin-nextjs"
